export const SET_LOGIN ="SET_LOGIN"
export const INIT_LOGIN ="INIT_LOGIN"
export const LOGIN_ERROR ="LOGIN_ERROR"
export const REMOVE_LOGIN ="REMOVE_LOGIN"
export const LOGIN_LOADER ="LOGIN_LOADER"
export const SET_DEFAULT = "SET_DEFAULT"
export const SET_USER = "SET_USER"
export const DEFAULT_LOGIN = "DEFAULT_LOGIN"

//All User
export const INIT_LIST_USER = "INIT_LIST_USER"
export const SUCCESS_LIST_USER = "SUCCESS_LIST_USER"
export const ERROR_LIST_USER = "ERROR_LIST_USER"
export const ADD_USER = "ADD_USER"
export const ERROR_USER = "ERROR_USER"
export const DELETE_USER = "DELETE_USER"
export const UPDATE_USER = "UPDATE_USER"
export const UPDATE_ERROR = "UPDATE_ERROR"
export const INIT_UPDATE_USER = "INIT_UPDATE_USER"